# Generated by Django 5.1.7 on 2025-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='last_date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_date_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reset_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ResetPattern',
        ),
    ]
